"""
Generates a styled PDF evaluation report from the structured JSON result.
Uses weasyprint (HTML -> PDF) — fastest path to a professional-looking
report without fighting a low-level PDF drawing API.
"""

import os
import uuid
import tempfile
from datetime import datetime

from weasyprint import HTML

TEMPLATE = """
<html>
<head>
<meta charset="utf-8">
<style>
  @page {{ size: A4; margin: 2cm; }}
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a1a; }}
  .header {{
    text-align: center;
    border-bottom: 3px solid #2b6cb0;
    padding-bottom: 12px;
    margin-bottom: 24px;
  }}
  .header h1 {{ margin: 0; color: #2b6cb0; letter-spacing: 1px; }}
  .header p {{ margin: 4px 0 0; color: #555; font-size: 12px; }}
  .meta {{ margin-bottom: 20px; font-size: 13px; }}
  .meta span {{ display: inline-block; margin-right: 24px; }}
  .score-box {{
    background: #ebf8ff;
    border: 1px solid #90cdf4;
    border-radius: 8px;
    text-align: center;
    padding: 18px;
    margin-bottom: 24px;
  }}
  .score-box .score {{ font-size: 36px; font-weight: bold; color: #2b6cb0; }}
  .score-box .label {{ font-size: 12px; color: #555; text-transform: uppercase; letter-spacing: 1px; }}
  table {{ width: 100%; border-collapse: collapse; margin-bottom: 24px; }}
  th, td {{ border: 1px solid #ddd; padding: 8px 10px; font-size: 13px; text-align: left; }}
  th {{ background: #f7fafc; color: #2b6cb0; }}
  .section-title {{
    font-size: 14px;
    font-weight: bold;
    color: #2b6cb0;
    border-bottom: 1px solid #cbd5e0;
    padding-bottom: 4px;
    margin-top: 24px;
    margin-bottom: 10px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }}
  ul {{ margin: 0; padding-left: 20px; font-size: 13px; }}
  li {{ margin-bottom: 4px; }}
  .strength {{ color: #2f855a; }}
  .weakness {{ color: #c05621; }}
  .footer {{
    margin-top: 40px;
    font-size: 10px;
    color: #999;
    text-align: center;
    border-top: 1px solid #eee;
    padding-top: 8px;
  }}
</style>
</head>
<body>
  <div class="header">
    <h1>NoteGrade AI</h1>
    <p>AI-Assisted Evaluation Report</p>
  </div>

  <div class="meta">
    <span><strong>Subject:</strong> {subject}</span>
    <span><strong>Question:</strong> {question}</span>
    <span><strong>Date:</strong> {date}</span>
  </div>

  <div class="score-box">
    <div class="label">Score</div>
    <div class="score">{marks_obtained} / {maximum_marks}</div>
  </div>

  <div class="section-title">Criteria Breakdown</div>
  <table>
    <tr><th>Criterion</th><th>Score</th><th>Feedback</th></tr>
    {criteria_rows}
  </table>

  <div class="section-title">Strengths</div>
  <ul>{strengths}</ul>

  <div class="section-title">Weaknesses</div>
  <ul>{weaknesses}</ul>

  <div class="section-title">Overall Feedback</div>
  <p style="font-size: 13px;">{overall_feedback}</p>

  <div class="section-title">Suggestions</div>
  <ul>{suggestions}</ul>

  <div class="footer">
    Generated by NoteGrade AI — AI-assisted evaluation. Please review before
    finalizing marks; AI grading may misread handwriting or misjudge partial credit.
  </div>
</body>
</html>
"""


def _li(items):
    if not items:
        return "<li>None noted.</li>"
    return "".join(f"<li>{i}</li>" for i in items)


def generate_pdf_report(subject: str, question: str, evaluation: dict) -> str:
    criteria_rows = ""
    for c in evaluation.get("criteria", []):
        criteria_rows += (
            f"<tr><td>{c.get('name','')}</td>"
            f"<td>{c.get('score','')} / {c.get('max_score','')}</td>"
            f"<td>{c.get('feedback','')}</td></tr>"
        )

    html_content = TEMPLATE.format(
        subject=subject or "N/A",
        question=question or "N/A",
        date=datetime.now().strftime("%d %b %Y, %I:%M %p"),
        marks_obtained=evaluation.get("marks_obtained", 0),
        maximum_marks=evaluation.get("maximum_marks", 0),
        criteria_rows=criteria_rows or "<tr><td colspan='3'>No criteria breakdown.</td></tr>",
        strengths=_li(evaluation.get("strengths", [])),
        weaknesses=_li(evaluation.get("weaknesses", [])),
        overall_feedback=evaluation.get("overall_feedback", ""),
        suggestions=_li(evaluation.get("suggestions", [])),
    )

    out_dir = tempfile.gettempdir()
    out_path = os.path.join(out_dir, f"notegrade_{uuid.uuid4().hex}.pdf")
    HTML(string=html_content).write_pdf(out_path)
    return out_path